### ISSUE TITLE
MoreShopItems erodetection character name not support Japanese?

### ISSUE THREAD

**Issue by lee89tw14** [ManlyMarco/KoikatuGameplayMods#47]
Noticed that seems if character name in Japanese, the ero detection just give up to show toast where and who is masturbation,
and if the name is Eng, then it will showing correctly.

plugin ver 2.1.1

**Comment by ManlyMarco** [comment]
It tries to translate the name, if that never finishes then the dialog won't appear <https://github.com/ManlyMarco/KoikatuGameplayMods/blob/94acef81d24b89749c2394e91327aa2d24f31dd6/src/KKS_MoreStoreItems/Features/EroDetectorFeat.cs#L84>

**Comment by lee89tw14** [comment]
umm, so you mean the plugin try to translate JPN to JPN?
anyway to disable it?

**Comment by ManlyMarco** [comment]
Oh, so you are running the game in Japanese? It should work as normal if you have autotranslator installed.

**Comment by lee89tw14** [comment]
Yes, I do have autotranslator plugin called Xunity Auto Translator and Text
Resource Redirector, but still it couldn't show the character name and
location in JPN correctly.(Tried to disable them and the game won't load,
Disable all the options in Text Resource Redirector but change nothing)
I have some character card that the name is in ENG, and it will show
correctly, but only could see the name of which character is doing the
thing, location also will not showing correctly.
And I have the game file from better repack, I wonder if this issue only
happening there, haven't really test it yet.

2023年4月15日(土) 6:09 ManlyMarco ***@***.***>:

**Comment by lee89tw14** [comment]
[log of ENG.log](https://github.com/ManlyMarco/KoikatuGameplayMods/files/11241120/log.of.ENG.log)
[log of JPN.log](https://github.com/ManlyMarco/KoikatuGameplayMods/files/11241121/log.of.JPN.log)

ok, so here are the logs that game in JPN and ENG, which is auto generated in BeplnEx folder

**Comment by ManlyMarco** [comment]
Sorry for the delay, this version should fix it. [KKS_MoreShopItems_test.zip](https://github.com/ManlyMarco/KoikatuGameplayMods/files/11362261/KKS_MoreShopItems_test.zip)

**Comment by lee89tw14** [comment]
![image](https://user-images.githubusercontent.com/22855239/235434881-6182f804-9949-4cd6-80d0-c9c050b971fb.png)
I just test it quickly, and seems it was fixed but not quite fixed
[LogOutput with only 1cha.log](https://github.com/ManlyMarco/KoikatuGameplayMods/files/11364766/LogOutput.with.only.1cha.log)

here are the log and pic, the toast was appear correctly but name and place not showing correctly


[output_log with only 1cha.txt](https://github.com/ManlyMarco/KoikatuGameplayMods/files/11364767/output_log.with.only.1cha.txt)
s now appear correctly but place and name were missing.
[output_log.txt](https://github.com/ManlyMarco/KoikatuGameplayMods/files/11364717/output_
[LogOutput.log](https://github.com/ManlyMarco/KoikatuGameplayMods/files/11364719/LogOutput.log)
log.txt)

**Comment by ManlyMarco** [comment]
I believe this should fix it fully [KKS_MoreShopItems_test2.zip](https://github.com/ManlyMarco/KoikatuGameplayMods/files/11381010/KKS_MoreShopItems_test2.zip)

**Comment by lee89tw14** [comment]
Yes, it fixed the issue, thanks for your time to fix this.
